# Generated by Django 2.2 on 2020-07-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('service_type', models.TextField()),
                ('bill_titlefront', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(max_digits=100, decimal_places=2, blank=True, null=True)),
                ('termsandconditions', models.CharField(max_length=100)),
                ('fulldescription', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=100)),
                ('gsttotal', models.CharField(max_length=100)),
                ('gstpercentage', models.CharField(max_length=100)),
                ('service', models.TextField(max_length=100)),
                ('currency', models.TextField(max_length=100)),
                ('footer', models.TextField(max_length=100)),
                ('bill_titleback', models.CharField(max_length=100)),
                ('bill_title', models.CharField(max_length=100)),

            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
    ]
